module Cisco-IOS-XE-skip {
  namespace "http://cisco.com/ns/yang/Cisco-IOS-XE-skip";
  prefix ios-skip;

  import cisco-semver {
    prefix cisco-semver;
  }
  import Cisco-IOS-XE-native {
    prefix ios;
  }
  import Cisco-IOS-XE-ntp {
    prefix ios-ntp;
  }
  import Cisco-IOS-XE-bgp {
    prefix ios-bgp;
  }
  import Cisco-IOS-XE-acl {
    prefix ios-acl;
  }
  import Cisco-IOS-XE-snmp {
    prefix ios-snmp;
  }
  import Cisco-IOS-XE-object-group {
    prefix ios-og;
  }
  import Cisco-IOS-XE-multicast {
    prefix ios-mc;
  }  

  organization
    "Bloomberg LP";

  revision 2025-06-06 {
    description
      "First not-supported list";
    cisco-semver:module-version "0.2.0";
  }

  //============================= Interfaces ==================================
  deviation "/ios:native/ios:interface/ios:FastEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:FiveGigabitEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:AppGigabitEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:TwentyFiveGigabitEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:TwoGigabitEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Tunnel" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Virtual-Template" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Dialer" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:AppNav-Compress" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:AppNav-UnCompress" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:ATM" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:ATM-subinterface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Async" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:BD-VIF" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:BDI" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Cellular" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Embedded-Service-Engine" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Ethernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:LISP" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Multilink" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Port-channel" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:SM" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Serial" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:VirtualPortGroup" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:nve" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Vif" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Wlan-GigabitEthernet" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:MFR" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:MFR-subinterface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Serial-subinterface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:ucse" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Ethernet-Internal" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Service-Engine" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:LISP-subinterface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Port-channel-subinterface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:GMPLS" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Group-Async" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:Virtual-PPP" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:vasileft" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:interface/ios:vasiright" {
    deviate not-supported;
  }

  //============================= NTP ==================================
  deviation "/ios:native/ios:ntp/ios-ntp:access-group/ios-ntp:ipv6" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ntp/ios-ntp:source" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ntp/ios-ntp:peer" {
    deviate not-supported;
  }

  //============================= BGP ==================================
  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:bmp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:bgp/ios-bgp:rpki" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:template" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:with-vrf" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:vpnv4" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:nsap" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:link-state" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:rtfilter" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:l2vpn" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:ipv6" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:router/ios-bgp:bgp/ios-bgp:address-family/ios-bgp:no-vrf/ios-bgp:vpnv6" {
    deviate not-supported;
  } 

  //============================= NAT ==================================
  deviation "/ios:native/ios:nat64" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:nat66" {
    deviate not-supported;
  }

  //============================= Object Group ==================================
  deviation "/ios:native/ios:object-group/ios-og:fqdn/ios-og:name" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:object-group" {
    deviate not-supported;
  }

  //============================= ACL ==================================
  deviation "/ios:native/ios:ipv6/ios:access-list" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-acl:access-list/ios-acl:acl-limit" {
    deviate not-supported;
  }
  
  deviation "/ios:native/ios:ip/ios-acl:access-list/ios-acl:fqdn" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios-acl:access-list/ios-acl:role-based" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios-acl:access-list/ios-acl:helper" {
    deviate not-supported;
  }

  //============================= IPv6 ==================================
  deviation "/ios:native/ios:ipv6" {
    deviate not-supported;
  } 

  //============================= MAC ==================================
  deviation "/ios:native/ios:mac" {
    deviate not-supported;
  } 

  //============================= Root ==================================
  deviation "/ios:native/ios:alarm-contact" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:archive" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:clock" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:control-plane" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:domain" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:eap" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:enable" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:errdisable" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:fabric" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:hw-module" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:identity" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:lacp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:license" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:location" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:mab" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:mac-address-table" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:macro" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:memory" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:memory-size" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:monitor" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:mpls" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:parser" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:pfr" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:pfr-map" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:process" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:privilege" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:redundancy" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:scheduler" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:service/ios:alignment" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:service/ios:heartbeat" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:service/ios:pad" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:service/ios:timestamps/ios:debug" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:standby" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:time-range" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:transceiver" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:transport-map" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:tftp-server-config" {
    deviate not-supported;
  }

  //============================= LINE ==================================
  deviation "/ios:native/ios:line/ios:aux" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:line/ios:line-list" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:line/ios:async-line" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:line/ios:async-line-single" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:line/ios:async-line-range" {
    deviate not-supported;
  } 

  //============================= IP ==================================
  deviation "/ios:native/ios:ip/ios:domain/ios:lookup-settings" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:ip/ios-mc:mroute" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:ip/ios-mc:msdp" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:ip/ios:explicit-path" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios:ip/ios:forward-protocol" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:sdwan" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:arp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:prefix-list" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:admission" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:ftp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:tftp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:ip/ios:local" {
    deviate not-supported;
  }

  //============================= RMON ==================================
  deviation "/ios:native/ios:rmon" {
    deviate not-supported;
  }

  //============================= SNMP ==================================
  deviation "/ios:native/ios:snmp" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:engineID" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:group" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:source-interface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:user" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:trap" {
    deviate not-supported;
  }

  deviation "/ios:native/ios:snmp-server/ios-snmp:trap-source" {
    deviate not-supported;
  }

  //============================= ROUTE-MAP ==================================
  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-without-order-seq" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:additional-paths" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:as-path" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:community" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:extcommunity" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:ipv6" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:rpki" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:source-protocol" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:match/ios-route-map:route-type" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:as-path" {
    deviate not-supported;
  } 

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:comm-list" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:community" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:extcomm-list" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:extcommunity" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:interface" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:ipv6" {
    deviate not-supported;
  }

  deviation "/ios:native/ios-route-map:route-map/ios-route-map:route-map-seq/ios-route-map:set/ios-route-map:dampening" {
    deviate not-supported;
  }
}